In [2]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(3,)


In [5]:
print(arr1[2])

3


In [6]:
arr1[2]=5
print(arr1)

[1 2 5]


In [7]:
arr2 = np.array([[1,2,3],[3,4,5]])
print(arr2)

[[1 2 3]
 [3 4 5]]


In [8]:
print(arr2[1][2])

5


In [9]:
print(arr2[1,2])

5


In [10]:
print(arr2.shape)

(2, 3)


In [11]:
print(arr2[1][-2])

4


In [13]:
arrS = np.array(["china", "india", "usa", "maxico"])
print(arrS)

['china' 'india' 'usa' 'maxico']


In [14]:
arrS

array(['china', 'india', 'usa', 'maxico'], dtype='<U6')

In [15]:
arrR = np.arange(0,20,2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arrL = np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
arr = np.random.rand(10)
arr

array([0.17844502, 0.20841032, 0.53250721, 0.44903213, 0.00549049,
       0.31414382, 0.12476515, 0.67945808, 0.60923985, 0.61703697])

In [18]:
arr = np.random.rand(3,4)
arr

array([[0.54621709, 0.0931658 , 0.28711131, 0.21835982],
       [0.20814223, 0.20384259, 0.83641324, 0.0114741 ],
       [0.03456348, 0.181287  , 0.11713275, 0.61903211]])

In [20]:
print(np.zeros(10))
print("\n")
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(np.ones((4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
print(np.ones((4,5,6)))

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [23]:
arrG = [0,1,2]
print(np.repeat(arrG,3))

[0 0 0 1 1 1 2 2 2]


In [24]:
print(np.tile(arrG,3))

[0 1 2 0 1 2 0 1 2]


In [26]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([1,2,3,4,5])


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
arrM = np.random.rand(5,5)
arrM

array([[0.55396878, 0.49671998, 0.47227815, 0.02974042, 0.04686496],
       [0.44325537, 0.9636147 , 0.31204937, 0.35687971, 0.56637797],
       [0.78795592, 0.74758396, 0.67715824, 0.05928353, 0.73823148],
       [0.50063007, 0.23834378, 0.49901515, 0.6447407 , 0.22478043],
       [0.20560941, 0.77758905, 0.56762263, 0.0832297 , 0.93551078]])

In [30]:
np.diag(arrM)

array([0.55396878, 0.9636147 , 0.67715824, 0.6447407 , 0.93551078])

In [31]:
arrM.ndim

2

In [32]:
arrM.size

25

In [33]:
arrM.shape

(5, 5)

In [34]:
np.random.randint(-10,10,4)

array([ 3,  4, -8,  9], dtype=int32)

In [35]:
arr+10

array([[10.54621709, 10.0931658 , 10.28711131, 10.21835982],
       [10.20814223, 10.20384259, 10.83641324, 10.0114741 ],
       [10.03456348, 10.181287  , 10.11713275, 10.61903211]])

In [36]:
arr*2

array([[1.09243418, 0.18633159, 0.57422262, 0.43671964],
       [0.41628445, 0.40768519, 1.67282647, 0.0229482 ],
       [0.06912697, 0.362574  , 0.23426549, 1.23806422]])

In [38]:
arr/2

array([[0.27310854, 0.0465829 , 0.14355565, 0.10917991],
       [0.10407111, 0.1019213 , 0.41820662, 0.00573705],
       [0.01728174, 0.0906435 , 0.05856637, 0.30951606]])

In [39]:
np.exp(arr)

array([[1.72670866, 1.09764371, 1.33257253, 1.24403461],
       [1.23138829, 1.22610514, 2.3080736 , 1.01154018],
       [1.03516774, 1.19875918, 1.12426866, 1.85712968]])

In [40]:
arr

array([[0.54621709, 0.0931658 , 0.28711131, 0.21835982],
       [0.20814223, 0.20384259, 0.83641324, 0.0114741 ],
       [0.03456348, 0.181287  , 0.11713275, 0.61903211]])

In [41]:
np.log2(arr)

array([[-0.87245364, -3.42405579, -1.80031794, -2.19522069],
       [-2.26435842, -2.29447256, -0.2577122 , -6.44547527],
       [-4.85460759, -2.4636526 , -3.09378362, -0.69191384]])

In [43]:
np.log10(arr)

array([[-0.26263472, -1.0307435 , -0.5419497 , -0.66082727],
       [-0.68163981, -0.69070506, -0.0775791 , -1.94028139],
       [-1.4613825 , -0.74163333, -0.93132167, -0.20828682]])

In [44]:
np.tan(arr)

array([[0.60791233, 0.09343629, 0.29526956, 0.22189785],
       [0.21120104, 0.20671366, 1.10761343, 0.0114746 ],
       [0.03457725, 0.18329946, 0.11767139, 0.71244883]])

In [45]:
arr

array([[0.54621709, 0.0931658 , 0.28711131, 0.21835982],
       [0.20814223, 0.20384259, 0.83641324, 0.0114741 ],
       [0.03456348, 0.181287  , 0.11713275, 0.61903211]])

In [46]:
np.sum(arr)

np.float64(3.3567415151717195)

In [47]:
np.sum(arr, axis=0)

array([0.7889228 , 0.47829539, 1.24065729, 0.84886603])

In [49]:
np.sum(arr, axis=1)

array([1.14485401, 1.25987216, 0.95201535])

In [50]:
np.min(arr)

np.float64(0.011474099374546354)

In [52]:
np.min(arr, axis=1)

array([0.0931658 , 0.0114741 , 0.03456348])

In [53]:
np.max(arr)

np.float64(0.8364132371366677)

In [54]:
np.max(arr, axis=0)

array([0.54621709, 0.20384259, 0.83641324, 0.61903211])

In [55]:
np.mean(arr, axis=0)

array([0.26297427, 0.1594318 , 0.41355243, 0.28295534])

In [56]:
np.median(arr, axis=0)

array([0.20814223, 0.181287  , 0.28711131, 0.21835982])

In [57]:
np.std(arr)

np.float64(0.24388264786201058)

In [58]:
np.var(arr)

np.float64(0.05947874592818545)

In [59]:
arr[1:,2:4]

array([[0.83641324, 0.0114741 ],
       [0.11713275, 0.61903211]])

In [60]:
np.sort(arr, axis=0)

array([[0.03456348, 0.0931658 , 0.11713275, 0.0114741 ],
       [0.20814223, 0.181287  , 0.28711131, 0.21835982],
       [0.54621709, 0.20384259, 0.83641324, 0.61903211]])

In [61]:
np.sort(arr, axis=1)

array([[0.0931658 , 0.21835982, 0.28711131, 0.54621709],
       [0.0114741 , 0.20384259, 0.20814223, 0.83641324],
       [0.03456348, 0.11713275, 0.181287  , 0.61903211]])

In [62]:
arr.T

array([[0.54621709, 0.20814223, 0.03456348],
       [0.0931658 , 0.20384259, 0.181287  ],
       [0.28711131, 0.83641324, 0.11713275],
       [0.21835982, 0.0114741 , 0.61903211]])

In [63]:
arrB = np.array([4,5,6,7,8])
arrB

array([4, 5, 6, 7, 8])

In [64]:
arrD = np.append(arrB,8)
arrD

array([4, 5, 6, 7, 8, 8])

In [67]:
arrO = np.insert(arrB,0,[1,2,3])
arrO

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
print(np.max(arrO))

8


In [70]:
arr5 = np.delete(arrO,[1,3])
arr5

array([1, 3, 5, 6, 7, 8])

In [71]:
arrC = arr5.copy()
arrC

array([1, 3, 5, 6, 7, 8])

In [73]:
arr6 = np.array([[1,2,3,4],[1,2,3,4]])
arr7 = np.array([[5,6,7,8],[5,6,7,8]])
arrcat = np.concatenate((arr6,arr7), axis=0)
print(arrcat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [74]:
arr6 = np.array([[1,2,3,4],[1,2,3,4]])
arr7 = np.array([[5,6,7,8],[5,6,7,8]])
arrcat = np.concatenate((arr6,arr7), axis=1)
print(arrcat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [75]:
catV = np.vstack((arr6,arr7))
catV

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [78]:
catH = np.hstack((arr6,arr7))
catH

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [79]:
arr8 = np.array([1,2,3,1,22,2,2,3,3,2,1,3,4,5,6,7,8,9,6,7,8,9,4,3,1,5,6,7,8])
np.unique(arr8)               

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 22])

In [81]:
uniques, counts = np.unique(arr8, return_counts=True)
print(uniques)
print(counts)

[ 1  2  3  4  5  6  7  8  9 22]
[4 4 5 2 2 3 3 3 2 1]


In [82]:
# intersection, differentiation, neither
arr6 = np.array([1,2,3,4,4,5,6,7])
arr7 = np.array([5,6,7,8,4,3])
np.intersect1d(arr6, arr7)

array([3, 4, 5, 6, 7])

In [83]:
arr6 = np.array([1,2,3,4,4,5,6,7])
arr7 = np.array([5,6,7,8,4,3])
np.union1d(arr6, arr7)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
arr6 = np.array([1,2,3,4,4,5,6,7])
arr7 = np.array([5,6,7,8,4,3])
np.setdiff1d(arr6, arr7)

array([1, 2])

In [85]:
arr6 = np.array([1,2,3,4,4,5,6,7])
arr7 = np.array([5,6,7,8,4,3])
np.setxor1d(arr6, arr7)

array([1, 2, 8])